name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Nie przejmuj się bratku, to jest do zrobienia' first issue"
        pr-message: "Dzięki za pull requesta, ale jeszcze nie merguj, trzeba najpierw przejrzeć zmiany' first pull request"
